Scrum 20 ordering
BeattLau/E-commerceFinalProject pull request #13
Opened 2024-02-05 12:21 UTC by BeattLau

updates to config files trying to fix authentication and jwt problems
added files for ordering (entity, service, repository)

2024-02-05 17:01 UTC, MenilV requested changes
a few things to check first, but great overall

2024-02-05 17:01 UTC, MenilV commented on src/main/java/com/ecommerce/Config/JwtAuthenticationFilter.java
> +        System.out.println("Authorization: " + authHeader);
lets remove printlns

2024-02-05 17:01 UTC, MenilV commented on src/main/java/com/ecommerce/Config/JwtAuthenticationFilter.java
> +        System.out.println("Authorization Header: " + authHeader);
let's remove println

2024-02-05 17:01 UTC, MenilV commented on src/main/java/com/ecommerce/Controller/UserController.java
> +            return ResponseEntity.status(HttpStatus.UNAUTHORIZED).body("Authentication failed");
instead of `String` let's response with a JSON

2024-02-05 17:01 UTC, MenilV commented on src/main/java/com/ecommerce/Service/OrderServiceImpl.java
> +            throw new AccessDeniedException("You do not have permission to access this resource");
does this get caught by a global exception handler?

2024-02-06 08:38 UTC, BeattLau commented on src/main/java/com/ecommerce/Config/JwtAuthenticationFilter.java
> +        System.out.println("Authorization: " + authHeader);
Updated, see commit bc7d0ea

2024-02-06 08:38 UTC, BeattLau commented on src/main/java/com/ecommerce/Config/JwtAuthenticationFilter.java
> +        System.out.println("Authorization Header: " + authHeader);
Updated, see commit bc7d0ea

2024-02-06 08:38 UTC, BeattLau commented on src/main/java/com/ecommerce/Controller/UserController.java
> +            return ResponseEntity.status(HttpStatus.UNAUTHORIZED).body("Authentication failed");
Update, see commit 3b95a5d

2024-02-06 13:06 UTC, BeattLau commented on src/main/java/com/ecommerce/Service/OrderServiceImpl.java
> +            throw new AccessDeniedException("You do not have permission to access this resource");
I still have some work to do with my global exception handler

2024-02-07 08:55 UTC, faruka-startsteps approved these changes

2024-02-07 08:55 UTC, faruka-startsteps commented on src/main/java/com/ecommerce/Controller/OrderController.java
> +        double totalValue = cart.getTotalValue();
can you move this logic to a service?

2024-02-07 09:10 UTC, merged